FROM node:20.11.1-bullseye
RUN apt-get update && apt-get upgrade -y && apt-get install -y tini
  WORKDIR /app

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .

ENTRYPOINT ["tini", "--", "./local/entrypoint.sh"]
