on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.
      ref:
        type: string
        required: true
        description: The tag or SHA to checkout.

env:
  GCP_PROJECT: r253-dev
  ARTIFACT_REPOSITORY: nest-development
  IMAGE_NAME: nest-${{ inputs.environment }}
  FULL_IMAGE_NAME: asia-northeast2-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast2-docker.pkg.dev

      - name: Build
        run: |
          docker build -t ${{ env.FULL_IMAGE_NAME }} ./

      - name: Push
        run: |
          docker push ${{ env.FULL_IMAGE_NAME }}
