on:
  push:
    branches: [develop, fix/migrate-region]
  release:
    types:
      - published

jobs:
  development:
    if: github.ref == 'refs/heads/fix/migrate-region'
    uses: ./.github/workflows/_deployment.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: development
      ref: ${{ github.sha }}
    secrets: inherit
  production:
    if: github.event_name == 'release'
    uses: ./.github/workflows/_deployment.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: production
      ref: ${{ github.sha }}
    secrets: inherit
