on:
  push:
    branches: [fix/migration-socket]

jobs:
  migration_development:
    name: migration_development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          create_credentials_file: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: npm

      - name: Output versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
          mkdir /tmp/cloudsql
          ./cloud_sql_proxy -dir=/tmp/cloudsql -instances=${{ secrets.CLOUD_SQL_INSTANCE_ID }} &

      - name: Wait for Cloud SQL Proxy
        run: sleep 5

      - name: Run build
        run: npm run build:db

      - name: Run migration
        run: npm run db:migrate
        env:
          RDB_MIGRATION_URL: mysql://nest_development:nest_development@localhost/nest_development
