on:
  push:
    branches: [fix/migration-socket]

jobs:
  migration_development:
    name: migration_development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: npm

      - name: Output versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
          mkdir /tmp/cloudsql
          ./cloud_sql_proxy -dir=/tmp/cloudsql -instances=${{ secrets.CLOUD_SQL_INSTANCE_ID }}=tcp:3306 &

      - name: Wait for Cloud SQL Proxy
        run: sleep 5

      - name: Run build
        run: npm run build:db

      - name: Run migration
        run: npm run db:migrate
        env:
          DATABASE: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: localhost
          # RDB_MIGRATION_URL の設定を更新して、Cloud SQL Proxy 経由で接続するように修正
          RDB_MIGRATION_URL: 'mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@${{ env.DB_HOST }}/${{ secrets.DATABASE }}'
