on:
  push:
    branches: [feature/sequelize-administrator]

env:
  GCP_PROJECT_NUMBER: 976519973151

jobs:
  migration:
    name: migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Retrieve database configuration secrets
        run: |
          echo "DATABASE=$(gcloud secrets versions access latest --secret=SEKURETO --project=${{ env.GCP_PROJECT_NUMBER }})" >> $GITHUB_ENV
