on:
  push:
    branches: [feature/sequelize-administrator]

env:
  GCP_PROJECT_NUMBER: 976519973151

jobs:
  migration:
    name: migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.GCP_PROJECT_NUMBER }}
          export_default_credentials: true

      - name: Install Beta Components
        run: gcloud components install beta --quiet

      - name: Debug Project Info
        run: gcloud projects describe ${{ env.GCP_PROJECT_NUMBER }}

      - name: 'Get Secret with Debugging'
        run: gcloud secrets versions access latest --secret=SEKURETO --project ${{ env.GCP_PROJECT_NUMBER }} --verbosity=debug
        continue-on-error: true
